Remove the build folder for unit test to ensure correctness (#3143)
Fix the occasionally issue in TestTaskScriptRunner

### Description

Sometimes the unit test failed because there is a "build" dir, this will
lead to test failure:
```
AssertionError: Lists differ: ['/ho[28 chars]VFlare-premerge/build/lib/nvflare/cli.py', '--batch_size', '4'] != ['/ho[28 chars]VFlare-premerge/nvflare/cli.py', '--batch_size', '4']
```

That build dir is generated by pip install and can be removed during the
unit test phase to ensure correctness

### Types of changes
<!--- Put an `x` in all the boxes that apply, and remove the not
applicable items -->
- [x] Non-breaking change (fix or new feature that would not break
existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing
functionality to change).
- [ ] New tests added to cover the changes.
- [x] Quick tests passed locally by running `./runtest.sh`.
- [ ] In-line docstrings updated.
- [ ] Documentation updated.